name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  # Force colored output in CI
  FORCE_COLOR: 1

jobs:
  linux:
    name: Linux Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build
        
    - name: Build extension
      run: |
        echo "Building YAML extension..."
        make release
        echo "Build completed successfully"
        
    - name: Check build artifacts
      run: |
        echo "Checking for built extension..."
        ls -la build/release/extension/yaml/ || echo "Extension directory not found"
        file build/release/extension/yaml/yaml.duckdb_extension || echo "Extension file not found"
        
    - name: Run tests
      run: |
        make test
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: linux-extension
        path: |
          build/release/extension/yaml/yaml.duckdb_extension
        
  macos:
    name: macOS Build
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        brew install ninja
        
    - name: Build extension
      run: |
        make release
        
    - name: Run tests
      run: |
        make test
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-extension
        path: |
          build/release/extension/yaml/yaml.duckdb_extension
        
  windows:
    name: Windows Build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        choco install ninja
        
    - name: Build extension
      shell: bash
      run: |
        make release
        
    - name: Run tests
      shell: bash
      run: |
        make test
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-extension
        path: |
          build/release/extension/yaml/yaml.duckdb_extension
          
  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [linux, macos, windows]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          linux-extension/yaml.duckdb_extension
          macos-extension/yaml.duckdb_extension
          windows-extension/yaml.duckdb_extension
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}